[project]
name = "fastapi-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "quarto>=0.1.0",
    "ruff>=0.11.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
